// Hardcoded Canonical Sample Audit Report
// Strictly adheres to Performance Preservation Mode:
// - Only models with better/equal rank (<= baselineRank) and lower cost (< currentCost) are recommended.
// - Allocations with no rank-preserving cheaper alternatives are marked as "Already Optimized" ($0 savings).

export const SAMPLE_AUDIT_DATA = {
  _id: 'sample_audit_2026',
  userId: 'sample_enterprise_user',
  createdAt: '2026-07-21T23:13:00.000Z',
  teamSize: 11,
  useCase: 'Coding & Mixed Workloads',
  optimizationGoal: 'performance',
  costCutPercentage: 50,
  isUnlocked: true,
  totalCurrentCost: 319.96,
  tierUsed: 'pro',
  selectedOptions: {
    '0': 'subscription',
    '1': 'subscription',
    '2': 'subscription',
    '3': 'subscription',
    '4': 'subscription',
    '5': 'subscription',
    '6': 'subscription'
  },
  allocations: [
    {
      _id: 'alloc_openai',
      type: 'subscription',
      toolName: 'OpenAI',
      plan: 'ChatGPT Plus',
      seats: 1,
      purpose: 'Mixed',
      pricePerSeat: 20.00,
      currentCost: 20.00,
      baselineModels: ['GPT-5.6 Sol (high)', 'GPT-5.5 (medium)', 'GPT-4o mini'],
      baselineModelId: 'openai/gpt-5-6-sol-high'
    },
    {
      _id: 'alloc_anthropic',
      type: 'subscription',
      toolName: 'Anthropic',
      plan: 'Claude Pro',
      seats: 5,
      purpose: 'Mixed',
      pricePerSeat: 25.00,
      currentCost: 125.00,
      baselineModels: ['Claude Opus 5', 'Claude 3.7 Sonnet', 'Claude 3.5 Haiku'],
      baselineModelId: 'anthropic/claude-opus-5'
    },
    {
      _id: 'alloc_google',
      type: 'subscription',
      toolName: 'Google',
      plan: 'Gemini Advanced',
      seats: 1,
      purpose: 'Mixed',
      pricePerSeat: 19.99,
      currentCost: 19.99,
      baselineModels: ['Gemini 3.0 Pro', 'Gemini 3.5 Flash'],
      baselineModelId: 'google/gemini-3-0-pro'
    },
    {
      _id: 'alloc_claude_fable',
      type: 'api',
      toolName: 'Anthropic: Claude Fable 5',
      modelId: 'anthropic/claude-fable-5',
      seats: 1,
      purpose: 'Coding',
      inputTokens: 10000000,
      outputTokens: 2500000,
      currentCost: 124.99,
      baselineModels: ['Claude Fable 5 (Adaptive Reasoning, Max Effort)'],
      baselineModelId: 'anthropic/claude-fable-5'
    },
    {
      _id: 'alloc_mistral',
      type: 'subscription',
      toolName: 'Mistral',
      plan: 'Le Chat Pro',
      seats: 2,
      purpose: 'Coding',
      pricePerSeat: 14.99,
      currentCost: 29.98,
      baselineModels: ['Mistral Large', 'Codestral 25.01'],
      baselineModelId: 'mistralai/mistral-large'
    },
    {
      _id: 'alloc_meta',
      type: 'subscription',
      toolName: 'Meta',
      plan: 'Meta One',
      seats: 1,
      purpose: 'Research',
      pricePerSeat: 0.00,
      currentCost: 0.00,
      baselineModels: ['Llama 4 Maverick', 'Llama 3.3 70B'],
      baselineModelId: 'meta-llama/llama-4-maverick'
    },
    {
      _id: 'alloc_deepseek',
      type: 'subscription',
      toolName: 'DeepSeek',
      plan: 'Consumer',
      seats: 1,
      purpose: 'Data',
      pricePerSeat: 0.00,
      currentCost: 0.00,
      baselineModels: ['DeepSeek V4 Pro', 'DeepSeek V3.2'],
      baselineModelId: 'deepseek/deepseek-v4-pro'
    }
  ],
  savings: {
    totalMonthly: 116.99,
    totalAnnual: 1403.88,
    totalOptimizedSpend: 202.97,
    percentageSavings: 36.6,
    recommendations: [
      {
        _id: 'rec_openai',
        tool: 'OpenAI (1 seat for Mixed)',
        issue: 'Paying $20.00/mo for 1 ChatGPT Plus subscription license',
        action: 'Migrate to OpenAI ChatGPT Go ($8.00/mo) to preserve GPT-5.6 Sol access with $12.00/mo savings.',
        monthlySavings: 12.00,
        isAlreadyOptimized: false,
        originalAlloc: {
          type: 'subscription',
          toolName: 'OpenAI',
          plan: 'ChatGPT Plus',
          seats: 1,
          purpose: 'Mixed',
          currentCost: 20.00,
          provider: 'OpenAI',
          modelName: 'ChatGPT Plus'
        },
        apiOption: {
          name: 'GPT-5.6 Sol (max)',
          modelId: 'openai/gpt-5-6-sol',
          cost: 20.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Transition to direct API keys offers no rank-preserving cost advantage. Keep current OpenAI setup.',
          limits: 'Pay-as-you-go rates: $15.00/1M input, $75.00/1M output. Context: 1M tokens.',
          recommendedModel: 'GPT-5.6 Sol (max)',
          recommendedProvider: 'OpenAI',
          inputCostPerM: 15.00,
          outputCostPerM: 75.00,
          defaultInputTokens: 5000000,
          defaultOutputTokens: 1250000
        },
        subscriptionOption: {
          planName: 'OpenAI ChatGPT Go',
          cost: 8.00,
          savings: 12.00,
          isAlreadyOptimized: false,
          action: 'Migrate to the OpenAI ChatGPT Go subscription.',
          limits: '160 messages every 3 hours; includes GPT-5.6 Sol (max); 32K context window.',
          includedModels: ['GPT-5.6 Sol (max)', 'GPT-5.6 Sol (xhigh)', "GPT-4o mini Realtime (Dec '24)"],
          recommendedModel: 'ChatGPT Go',
          recommendedProvider: 'OpenAI'
        }
      },
      {
        _id: 'rec_anthropic',
        tool: 'Anthropic (5 seats for Mixed)',
        issue: 'Paying $125.00/mo across 5 Claude Pro subscription seats',
        action: 'Your current Anthropic Claude Pro subscription is already the highest-ranked option with optimal cost. Keep using it.',
        monthlySavings: 0.00,
        isAlreadyOptimized: true,
        statusText: 'Optimized',
        originalAlloc: {
          type: 'subscription',
          toolName: 'Anthropic',
          plan: 'Claude Pro',
          seats: 5,
          purpose: 'Mixed',
          currentCost: 125.00,
          provider: 'Anthropic',
          modelName: 'Claude Pro'
        },
        apiOption: {
          name: 'Claude Opus 5 (Adaptive Reasoning, Max Effort)',
          modelId: 'anthropic/claude-opus-5',
          cost: 125.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Transition to direct API keys offers no rank-preserving cost advantage. Keep current Anthropic setup.',
          limits: 'Pay-as-you-go rates: $15.00/1M input, $75.00/1M output. Context: 200K tokens.',
          recommendedModel: 'Claude Opus 5',
          recommendedProvider: 'Anthropic',
          inputCostPerM: 15.00,
          outputCostPerM: 75.00,
          defaultInputTokens: 25000000,
          defaultOutputTokens: 6250000
        },
        subscriptionOption: {
          planName: 'Anthropic Claude Pro',
          cost: 125.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current subscription is already the highest-ranked option with optimal cost. Keep using it.',
          limits: 'Includes Claude Opus 5 (Rank 1 overall & coding leader), Claude 3.7 Sonnet, and Claude 3.5 Haiku.',
          includedModels: ['Claude Opus 5', 'Claude 3.7 Sonnet', 'Claude 3.5 Haiku'],
          recommendedModel: 'Claude Pro',
          recommendedProvider: 'Anthropic'
        }
      },
      {
        _id: 'rec_google',
        tool: 'Google (1 seat for Mixed)',
        issue: 'Paying $19.99/mo for Gemini Advanced subscription',
        action: 'Your current Google Gemini Advanced subscription is already optimal. Keep using it.',
        monthlySavings: 0.00,
        isAlreadyOptimized: true,
        statusText: 'Optimized',
        originalAlloc: {
          type: 'subscription',
          toolName: 'Google',
          plan: 'Gemini Advanced',
          seats: 1,
          purpose: 'Mixed',
          currentCost: 19.99,
          provider: 'Google',
          modelName: 'Gemini Advanced'
        },
        apiOption: {
          name: 'Gemini 3.0 Pro (Thinking)',
          modelId: 'google/gemini-3-0-pro',
          cost: 19.99,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Transition to direct API keys offers no rank-preserving cost advantage. Keep current Google setup.',
          limits: 'Pay-as-you-go rates: $1.25/1M input, $5.00/1M output. Context: 1M tokens.',
          recommendedModel: 'Gemini 3.0 Pro',
          recommendedProvider: 'Google',
          inputCostPerM: 1.25,
          outputCostPerM: 5.00,
          defaultInputTokens: 5000000,
          defaultOutputTokens: 1250000
        },
        subscriptionOption: {
          planName: 'Google Gemini Advanced',
          cost: 19.99,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current Google Gemini Advanced subscription is already optimal. Keep using it.',
          limits: 'Includes Gemini 3.0 Pro and Gemini 3.5 Flash with 1M context.',
          includedModels: ['Gemini 3.0 Pro', 'Gemini 3.5 Flash'],
          recommendedModel: 'Gemini Advanced',
          recommendedProvider: 'Google'
        }
      },
      {
        _id: 'rec_claude_fable',
        tool: 'Anthropic: Claude Fable 5 API (12.5M tokens for Coding)',
        issue: 'Paying $124.99/mo for direct Claude Fable 5 API tokens',
        action: 'Migrate to Anthropic Claude Pro subscription ($20.00/mo) for full Claude Opus 5 (Rank 1) & Claude Fable 5 access with +$104.99/mo savings.',
        monthlySavings: 104.99,
        isAlreadyOptimized: false,
        originalAlloc: {
          type: 'api',
          toolName: 'Anthropic: Claude Fable 5',
          modelId: 'anthropic/claude-fable-5',
          seats: 1,
          purpose: 'Coding',
          currentCost: 124.99,
          provider: 'Anthropic',
          modelName: 'Claude Fable 5'
        },
        apiOption: {
          name: 'Claude Fable 5 (Adaptive Reasoning, Max Effort)',
          modelId: 'anthropic/claude-fable-5',
          cost: 124.99,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current model API is already the highest-ranked option with optimal cost. No migration required.',
          limits: 'Pay-as-you-go rates: $6.00/1M input, $26.00/1M output.',
          recommendedModel: 'Claude Fable 5',
          recommendedProvider: 'Anthropic',
          inputCostPerM: 6.00,
          outputCostPerM: 26.00,
          defaultInputTokens: 10000000,
          defaultOutputTokens: 2500000
        },
        subscriptionOption: {
          planName: 'Anthropic Claude Pro',
          cost: 20.00,
          savings: 104.99,
          isAlreadyOptimized: false,
          action: 'Migrate to the Anthropic Claude Pro subscription.',
          limits: 'Includes Claude Opus 5 (Rank 1 Coding) and Claude Fable 5 (Rank 3 Coding).',
          includedModels: ['Claude Opus 5', 'Claude Fable 5', 'Claude 3.7 Sonnet'],
          recommendedModel: 'Claude Pro',
          recommendedProvider: 'Anthropic'
        }
      },
      {
        _id: 'rec_mistral',
        tool: 'Mistral (2 seats for Coding)',
        issue: 'Paying $29.98/mo for 2 Le Chat Pro seats',
        action: 'Your current deployment is already optimal. No changes required.',
        monthlySavings: 0.00,
        isAlreadyOptimized: true,
        statusText: 'Optimized',
        originalAlloc: {
          type: 'subscription',
          toolName: 'Mistral',
          plan: 'Le Chat Pro',
          seats: 2,
          purpose: 'Coding',
          currentCost: 29.98,
          provider: 'Mistral',
          modelName: 'Le Chat Pro'
        },
        apiOption: {
          name: 'Codestral 25.01 (Coding Specialist)',
          modelId: 'mistralai/codestral-2501',
          cost: 29.98,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Transition to direct API keys offers no rank-preserving cost advantage. Keep current Mistral setup.',
          limits: 'Pay-as-you-go rates: $0.30/1M input, $0.90/1M output.',
          recommendedModel: 'Codestral 25.01',
          recommendedProvider: 'Mistral',
          inputCostPerM: 0.30,
          outputCostPerM: 0.90,
          defaultInputTokens: 10000000,
          defaultOutputTokens: 2500000
        },
        subscriptionOption: {
          planName: 'Mistral Le Chat Pro',
          cost: 29.98,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current subscription is already the highest-ranked option with optimal cost. Keep using it.',
          limits: 'Includes Codestral 25.01, Mistral Large, and Pixtral 12B.',
          includedModels: ['Codestral 25.01', 'Mistral Large', 'Pixtral 12B'],
          recommendedModel: 'Le Chat Pro',
          recommendedProvider: 'Mistral'
        }
      },
      {
        _id: 'rec_meta',
        tool: 'Meta (1 seat for Research)',
        issue: 'Using Meta AI free tier ($0.00/mo spend)',
        action: 'Your current deployment is already optimal. No changes required.',
        monthlySavings: 0.00,
        isAlreadyOptimized: true,
        statusText: 'Optimized',
        originalAlloc: {
          type: 'subscription',
          toolName: 'Meta',
          plan: 'Meta One',
          seats: 1,
          purpose: 'Research',
          currentCost: 0.00,
          provider: 'Meta',
          modelName: 'Meta One'
        },
        apiOption: {
          name: 'Llama 4 Maverick (Open Weights)',
          modelId: 'meta-llama/llama-4-maverick',
          cost: 0.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Current open model access is fully optimal.',
          limits: 'Free / self-hosted open weights.',
          recommendedModel: 'Llama 4 Maverick',
          recommendedProvider: 'Meta',
          inputCostPerM: 0.00,
          outputCostPerM: 0.00,
          defaultInputTokens: 5000000,
          defaultOutputTokens: 1250000
        },
        subscriptionOption: {
          planName: 'Meta Meta One',
          cost: 0.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current subscription is already optimal. Keep using it.',
          limits: 'Free access tier.',
          includedModels: ['Llama 4 Maverick', 'Llama 3.3 70B'],
          recommendedModel: 'Meta One',
          recommendedProvider: 'Meta'
        }
      },
      {
        _id: 'rec_deepseek',
        tool: 'DeepSeek (1 seat for Data)',
        issue: 'Using DeepSeek free access tier ($0.00/mo spend)',
        action: 'Your current deployment is already optimal. No changes required.',
        monthlySavings: 0.00,
        isAlreadyOptimized: true,
        statusText: 'Optimized',
        originalAlloc: {
          type: 'subscription',
          toolName: 'DeepSeek',
          plan: 'Consumer',
          seats: 1,
          purpose: 'Data',
          currentCost: 0.00,
          provider: 'DeepSeek',
          modelName: 'Consumer'
        },
        apiOption: {
          name: 'DeepSeek V4 Pro (Reasoning)',
          modelId: 'deepseek/deepseek-v4-pro',
          cost: 0.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Current data analysis setup is free and optimal.',
          limits: 'Standard access tier.',
          recommendedModel: 'DeepSeek V4 Pro',
          recommendedProvider: 'DeepSeek',
          inputCostPerM: 0.00,
          outputCostPerM: 0.00,
          defaultInputTokens: 5000000,
          defaultOutputTokens: 1250000
        },
        subscriptionOption: {
          planName: 'DeepSeek Consumer',
          cost: 0.00,
          savings: 0.00,
          statusText: 'Optimized',
          isAlreadyOptimized: true,
          action: 'Your current subscription is already optimal. Keep using it.',
          limits: 'Standard access tier.',
          includedModels: ['DeepSeek V4 Pro', 'DeepSeek V3.2'],
          recommendedModel: 'Consumer',
          recommendedProvider: 'DeepSeek'
        }
      }
    ]
  }
};
